### ISSUE TITLE
can't use monetdblite on windows (winerror 126)

### ISSUE THREAD

**Issue by erwinvink** [hannesmuehleisen/MonetDBLite#199]
After installing monetdblite with pip on a windows 10 machine, I'm not able to use monetdblite. when running a python file with only the following text: `import monetdblite`, I'm getting the following error:

`Traceback (most recent call last):
  File "C:/data_analytics/cryptobazen/main/monetdblite_test.py", line 5, in <module>
    import monetdblite
  File "C:\data_analytics\cryptobazen\virt_env\lib\site-packages\monetdblite\__init__.py", line 13, in <module>
    from monetdblite import connections
  File "C:\data_analytics\cryptobazen\virt_env\lib\site-packages\monetdblite\connections.py", line 7, in <module>
    from monetdblite import cursors
  File "C:\data_analytics\cryptobazen\virt_env\lib\site-packages\monetdblite\cursors.py", line 8, in <module>
    from monetdblite import embeddedmonetdb
  File "C:\data_analytics\cryptobazen\virt_env\lib\site-packages\monetdblite\embeddedmonetdb.py", line 32, in <module>
    libs[0]), mode=ctypes.RTLD_GLOBAL)
  File "C:\Users\Erwin\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found`

I've tried it on several windows computers but none of them worked. Visual C++ is not the problem. All needed packages are installed. Running on Linux is no problem. 

I tried debugging the path where this dll should be located, it looks fine. dll is in place. Tried to put the path to the dll hardcoded to avoid any errors in this, same error. Also tried to run dependency checker on the dll file, no missing dependencies found. Is this a known issue? What can I do?

**Comment by hannes** [comment]
@MarkRaasveldt windows builds are still unsolved, right?

**Comment by pakdev** [comment]
Correct. pip installing this module is definitely broken as it's only bundled with libmonetdb5.so, and I can't successfully build this project with mingw32-make. With some changes to the Makefile, I was able to compile successfully, but linking fails.

![image](https://user-images.githubusercontent.com/1248927/37936274-97eac6b8-311a-11e8-9ea1-c4d6a6e454a3.png)

**Comment by bilalahmed-gh** [comment]
Has this issue been resolved yet? We are facing this same error even today.

**Comment by hannes** [comment]
Please file this there: https://github.com/MonetDB/MonetDBLite-Python

**Comment by bilalahmed-gh** [comment]
> Please file this there: https://github.com/MonetDB/MonetDBLite-Python

Sure, Hannes. I'll file the issue there.
I just wanted to make sure that was anything done on it so far. Because I saw your comment from last year to Mark i.e. 

> @MarkRaasveldt windows builds are still unsolved, right?

**Comment by hannes** [comment]
It should be working these days. Check with @kutsurak ?

**Comment by kutsurak** [comment]
It is working (wheels install correctly and the test suite passes) for 64 bit installations and for Python >= 3.5. Unfortunately I have not been able to compile successfully for 32 bit versions or for Python 2.7.

**Comment by bilalahmed-gh** [comment]
I was able to install monetdblite finally after up installing the Visual C++ Build tools.
Steps I took:
1. pip install monetdblite" was not working and giving errors
2. I cloned from git using: "git clone https://github.com/hannesmuehleisen/MonetDBLite-Python.git"
3. Executed following statement: "python setup.py install"
4. It installed with many warnings
5. I executed python
6. entered command at python shell: "import monetdblite"
7. I got following error:
![monetdblite bug](https://user-images.githubusercontent.com/38028267/57525392-06c42900-7344-11e9-9223-d3bc0d6d9850.PNG)

**Comment by kutsurak** [comment]
Moved at: https://github.com/MonetDB/MonetDBLite-Python/issues/38
